fix out-of-bounds array access in export report.
cppcheck reports "gtk2_ardour/export_report.cc:260: error: Array 'y0[4]'
accessed at index 4, which is out of bounds.", which seems indeed to be
the case.