Revert "fix a cast warning (as recommended in GTK+ docs"
This reverts commit af30a6f001f0758155b3ece040fc2baa643a29de

because it breaks OSX/MacOS builds:
libs/surfaces/mackie/mackie_control_protocol.cc:945: error: 'G_SOURCE_FUNC' was not declared in this scope