Define timeval for MSVC in undo.h
I don't know if the include ardourext/misc.h line can be completely removed, so I've left that.

Solves the following errors (except for the error about gettimeofday):

ardour\libs\pbd\pbd\undo.h(84,22): error C2079: 'PBD::UndoTransaction::_timestamp' uses undefined struct 'PBD::timeval'
ardour\libs\pbd\pbd\undo.h(79,10): error C2440: 'return': cannot convert from 'const <error type>' to 'const PBD::timeval &'
ardour\libs\pbd\pbd\undo.h(79,10): note: Reason: cannot convert from 'const <error type>' to 'const PBD::timeval'
ardour\libs\pbd\pbd\undo.h(79,10): note: use of undefined type 'PBD::timeval'
ardour\libs\pbd\pbd\undo.h(72,29): note: see declaration of 'PBD::timeval'
ardour\libs\pbd\undo.cc(38,2): error C3861: 'gettimeofday': identifier not found
ardour\libs\pbd\undo.cc(147,8): error C2661: 'XMLNode::set_property': no overloaded function takes 1 arguments
ardour\libs\pbd\pbd\xml++.h(163,7): note: could be 'bool XMLNode::set_property(const char *,const T &)'
ardour\libs\pbd\undo.cc(147,8): note: 'bool XMLNode::set_property(const char *,const T &)': expects 2 arguments - 1 provided
ardour\libs\pbd\undo.cc(147,8): note: while trying to match the argument list '(const char [7])'
ardour\libs\pbd\undo.cc(148,8): error C2661: 'XMLNode::set_property': no overloaded function takes 1 arguments
ardour\libs\pbd\pbd\xml++.h(163,7): note: could be 'bool XMLNode::set_property(const char *,const T &)'
ardour\libs\pbd\undo.cc(148,8): note: 'bool XMLNode::set_property(const char *,const T &)': expects 2 arguments - 1 provided
ardour\libs\pbd\undo.cc(148,8): note: while trying to match the argument list '(const char [8])'