NO-OP sort includes - fixes macOS and --no-nls builds
Ardour's "pbd/i18n.h" needs to be included last,
after all template specialization, otherwise there will be
an ambiguity:

```
boost/function_types/detail/class_transform.hpp:23:26:
  error: ‘boost::mpl::placeholders::_’ has not been declared
  using mpl::placeholders::_;
```